### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by r0hin** [r0hin/echo#3]
Stuff like:

- ~~Verified~~ 45fdd610abab259ba094df6a6ef09b6e004065fb
- Bug Hunter
- Echo Team
- Official

Stuff like that

**Comment by r0hin** [comment]
✔️ Implemented verification badge across the UI 45fdd610abab259ba094df6a6ef09b6e004065fb 🚀

**Comment by SpeedyThingDev** [comment]
i need the uh cool badge

**Comment by r0hin** [comment]
ok
